### ISSUE TITLE
Invariant Violation: Tried to register two views with the same name RNSVGSvgView

### ISSUE THREAD

**Issue by luan-nvg** [vijaydemonz/react-native-liquid-progress-npm#1]
Invariant Violation: Tried to register two views with the same name RNSVGSvgView

**Comment by vijaydemonz** [comment]
Please explain your senario. if you can repoduce the issue in snack it would be great or put a screenshot It would be great.

**Comment by vijaydemonz** [comment]
Can not Reproduce.
