### ISSUE TITLE
Progress not fill correctly when decrease size

### ISSUE THREAD

**Issue by kbenteftifa** [vijaydemonz/react-native-liquid-progress-npm#2]
**Issue Description**
Unable to reduce the size of progress bar and still preserve the correct behavior.

**Explain what you did**
I change the size from 290 -> 125

`<LiquidProgress
        backgroundColor={"black"}
        frontWaveColor={"blue"}
        backWaveColor={"skyblue"}
        fill={value}
        size={125}
      > ... </LiquidProgress>`

**Screenshots**
Here's how it look with size={125}
<img width="200" alt="portfolio_view" src="https://user-images.githubusercontent.com/80801352/126075095-5450d48a-fb30-412e-81bf-7c947ee214a3.png">

The screen below if i changed it back to 290
<img width="200" alt="portfolio_view" src="https://user-images.githubusercontent.com/80801352/126075117-b86864a0-6c74-4f84-a664-3d06d0512953.png">

**Expected behavior**
If i set the value to 1, the liquid progress not show correctly (if i change it back to 290, it'll work)

**To Reproduce**
https://snack.expo.io/@vijaydemonz/react-native-liquid-progress

**Additional Information**
Same issue locally using react-native ~0.63.4.

**Comment by vijaydemonz** [comment]
Issue resolved in  #42cef95 commit. Please have a look.
