### ISSUE TITLE
Warning: Failed prop type: Invalid prop `size` of type `number` supplied to `LiquidProgress`, expected `string`. LiquidProgress@http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=com.gfxpubg&modulesOnly=false&runModule=true:129255:30

### ISSUE THREAD

**Issue by partyboyz** [vijaydemonz/react-native-liquid-progress-npm#3]
![Capture](https://user-images.githubusercontent.com/68802750/127685912-52653e83-682c-4e4b-ad8a-b66a357b78b6.PNG)

how to fix this problem??

**Comment by vijaydemonz** [comment]
Hi @partyboyz please install 1.0.4 version. i just updated or just see #cbbe431 commit to make local changes.if u still have any issue feel free to raise a new issue.
thanks for your contribution.

**Comment by partyboyz** [comment]
thxyuu
