### ISSUE TITLE
Warning prop-types size number misspell

### ISSUE THREAD

**Issue by kbenteftifa** [vijaydemonz/react-native-liquid-progress-npm#4]
**Issue Description**
Warning: Failed prop type: LiquidProgress: prop type `size` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.

**Explain what you did**
I change the propTypes of size from "Number" to "number" ( from index.js inside the node_modules ), after that the warning disappear.

Is this a temporary fix or there's a better way ?

**Comment by vijaydemonz** [comment]
@kbenteftifa  Thanks for raising issue. Changing things in node modules will not be good approach to solve this problem. The reason being you have to do same changes again and again when you install node_modules.

Please do install latest version (v1.0.5) of this package. this will resolve your problem.

Please let me know if you encounter any other issues.
